# Generated by Django 3.2 on 2023-04-03 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'No Setlist'), (1, 'Waiting Confirmation'), (2, 'Published')], default=0)),
                ('agree', models.ManyToManyField(blank=True, related_name='setlist_agree', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('disagree', models.ManyToManyField(blank=True, related_name='setlist_disagree', to=settings.AUTH_USER_MODEL)),
                ('gig', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setlist_gig', to='home.gig')),
                ('song', models.ManyToManyField(to='setlist.Song')),
            ],
            options={
                'ordering': ['gig__date'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('songs', models.ManyToManyField(related_name='releases', to='setlist.Song')),
            ],
        ),
    ]
