# Generated by Django 3.2 on 2022-06-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ['date']},
        ),
    ]
