# Generated by Django 3.2 on 2022-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0004_alter_setlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='status',
            field=models.IntegerField(choices=[(0, 'No Setlist'), (1, 'Waiting Confirmation'), (2, 'Published')], default=0),
        ),
    ]
