# Generated by Django 3.2 on 2023-04-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0005_alter_setlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlist',
            name='disagree',
        ),
    ]
