# Generated by Django 3.2 on 2023-04-01 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setlist', '0006_remove_setlist_disagree'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='disagree',
            field=models.ManyToManyField(blank=True, related_name='setlist_disagree', to=settings.AUTH_USER_MODEL),
        ),
    ]
