# Generated by Django 3.2 on 2022-06-30 08:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20220630_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'No Image'), (1, 'Image Waiting Confirmation'), (2, 'Published Image')], default=0)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gig')),
            ],
        ),
    ]
