# Generated by Django 3.2 on 2022-06-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220630_0846'),
        ('addimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gig',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_image', to='home.gig'),
        ),
    ]
