# Generated by Django 3.2 on 2022-07-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addimage', '0002_alter_image_gig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
