# Generated by Django 3.2 on 2023-04-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('setlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setlist.venue'),
        ),
    ]
