# Generated by Django 3.2 on 2022-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gig_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='image_status',
            field=models.IntegerField(choices=[(0, 'Waiting Confirmation'), (1, 'Published')], default=0),
        ),
    ]
