# Generated by Django 3.2 on 2022-07-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220701_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='featured_image_status',
            new_name='image_status',
        ),
    ]
