# Generated by Django 3.2 on 2022-07-02 19:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220701_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='image_status',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'No Image'), (1, 'Waiting Confirmation'), (2, 'Published')], default=0)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gig')),
            ],
        ),
    ]
