# Generated by Django 3.2 on 2022-07-02 20:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220702_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='gig',
            name='image_status',
            field=models.IntegerField(choices=[(0, 'No Image'), (1, 'Waiting Confirmation'), (2, 'Published')], default=0),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
